export const INCREMENT_COUNT = 'App/INCREMENT_COUNT';
export const DECREMENT_COUNT = 'App/DECREMENT_COUNT';
export const INCREMENT_COUNT_SUCCESS = 'App/INCREMENT_COUNT_SUCCESS';
export const DECREMENT_COUNT_SUCCESS = 'App/DECREMENT_COUNT_SUCCESS';
export const INCREMENT_COUNT_ERROR = 'App/INCREMENT_COUNT_ERROR';
export const DECREMENT_COUNT_ERROR = 'App/DECREMENT_COUNT_ERROR';
